<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */
function medibazar_child_enqueue_styles() {
    wp_enqueue_style( 'parent-style' , get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'medibazar-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( 'medibazar-style' ),
        wp_get_theme()->get('Version')
    );
}

add_action(  'wp_enqueue_scripts', 'medibazar_child_enqueue_styles', 99 );



function medibazar_child_theme_setup() {
    // Load the parent theme's text domain
    load_theme_textdomain('medibazar', get_template_directory() . '/languages');
    
    // Optionally, load the child theme's text domain if you add custom translations
    load_child_theme_textdomain('medibazar', get_stylesheet_directory() . '/languages');
}
add_action('after_setup_theme', 'medibazar_child_theme_setup');

// filter sort by in germna 
add_filter('woocommerce_catalog_orderby', 'custom_woocommerce_catalog_orderby_german');
function custom_woocommerce_catalog_orderby_german($orderby) {
    $orderby = array(
        'popularity' => __( 'Nach Beliebtheit sortieren', 'woocommerce' ),
        'rating'     => __( 'Nach Durchschnittsbewertung sortieren', 'woocommerce' ),
        'date'       => __( 'Nach Neuheit sortieren', 'woocommerce' ),
        'price'      => __( 'Nach Preis: niedrig zu hoch', 'woocommerce' ),
        'price-desc' => __( 'Nach Preis: hoch zu niedrig', 'woocommerce' ),
    );
    return $orderby;
}